
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose cổng Redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - devops
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - '5540:5540'
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis
    networks:
      - devops
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8080:8080" # Expose cổng Spring Boot
    depends_on:
      - redis
    networks:
      - devops
networks:
  devops:
    driver: bridge