version: '3.8'
services:
  web:  # Tên service (tự đặt)
    build: . # Build image từ Dockerfile trong thư mục hiện tại (.)
    ports:
      - "8080:8080"  # Ánh xạ cổng 8080 của container với cổng 8080 của host
    depends_on:
      - redis  # Service "web" phụ thuộc vào service "redis"
    environment:
      - REDIS_HOST=redis # Biến môi trường REDIS_HOST có giá trị là "redis"

  redis:  # Tên service (tự đặt)
    image: redis:latest  # Sử dụng image Redis mới nhất từ Docker Hub
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    - name: redis-data