server:
  ip: localhost
password: ''


spring:
  application:
    name: project_mobile_be

  datasource:
    url: jdbc:mysql://${server.ip}:3306/mobileproject
    username: root
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      import-check:
        enabled: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type:
          descriptor:
            sql:
              BasicBinder: org.hibernate.type.descriptor.sql.UUIDTypeDescriptor
              jdbc:
                fetch_size: 100
                batch_size: 30

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
    server:
      port: 8080
      file:
        upload-dir: C:\Users\Vinh\Desktop\project_mobile\project_mobile_be\src\main\java\tdc\edu\vn\project_mobile_be\services\impl
        springdoc:
          swagger-ui:
            enabled: true
          api-docs:
            enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thietasasasa@gmail.com
    password: wcrs zxrv wofz bfje
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt:
  signerKey: "CHpSZnAya03fnmgaxVnU9u4gdxZvnx+UFcrrC5i9+ZwI4+f5CNP0BlQEDCjNeyHh"
  valid-duration: 60
  refreshable-duration: 7

spring.devtools:
  restart:
    enabled: true  # Kích hoạt tự động tải lại
    exclude: static/**,public/** # Loại trừ thư mục static và public
  spring:
    jackson:
      time-zone: Asia/Ho_Chi_Minh

redis:
  host: ${server.ip}
  port: 6379
  password: ''
  cache:
    type: redis

google:
  cloud:
    storage:
      bucket-name: mobileproject
    credentials:
      path: service-account.json

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG


