spring:
  application:
    name: project_mobile_be

  datasource:
    url: jdbc:mysql://localhost:3306/mobileproject
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type:
          descriptor:
            sql:
              BasicBinder: org.hibernate.type.descriptor.sql.UUIDTypeDescriptor
              jdbc:
                fetch_size: 100
                batch_size: 30

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
    server:
      port: 8080
      file:
        upload-dir: C:\Users\Vinh\Desktop\project_mobile\project_mobile_be\src\main\java\tdc\edu\vn\project_mobile_be\services\impl
        springdoc:
          swagger-ui:
            enabled: true
          api-docs:
            enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thietasasasa@gmail.com
    password: wcrs zxrv wofz bfje
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt:
  signerKey: "CHpSZnAya03fnmgaxVnU9u4gdxZvnx+UFcrrC5i9+ZwI4+f5CNP0BlQEDCjNeyHh"
  valid-duration: 60
  refreshable-duration: 7

spring.devtools:
  restart:
    enabled: true  # Kích hoạt tự động tải lại
    exclude: static/**,public/** # Loại trừ thư mục static và public
  spring:
    jackson:
      time-zone: Asia/Ho_Chi_Minh

redis:
  host: 192.168.57.128
  port: 6379
  password: ''

google:
  cloud:
    storage:
      bucket-name: mobileproject
    credentials:
      path: src/main/resources/service-account.json

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

# Cấu hình Kafka
spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: products-group
    auto-offset-reset: earliest # Bắt đầu đọc từ đầu nếu không tìm thấy offset
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Cấu hình Debezium
debezium:
  datasource:
    url: jdbc:mysql://localhost:3306/mobileproject
    user: root
    password: ''
  kafka:
    topic: products  # Topic Kafka để Debezium gửi message đến
  database:
    server.name: my-app-connector # Tên duy nhất cho connector
    history:
      kafka:
        bootstrap-servers: localhost:9092
        topic: dbhistory.mobileproject # Topic Kafka để lưu trữ schema history
  table.include.list: mobileproject.products # Danh sách các bảng cần theo dõi