spring:
  application:
    name: project_mobile_be

  datasource:
    url: jdbc:mysql://localhost:3306/mobileproject
    username: "root"
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      org.hibernate.envers.store_data_at_delete: true
      hibernate:
        use_sql_comments: true
        format_sql: true
        type:
          descriptor:
            sql:
              BasicBinder: org.hibernate.type.descriptor.sql.UUIDTypeDescriptor
              jdbc:
                fetch_size: 100
                batch_size: 30

  servlet:
    multipart:
<<<<<<< HEAD
      max-file-size: 20MB
      max-request-size: 50MB

  server:
    port: 8080
    file:
      upload-dir: C:\\Users\\Vinh\\Desktop\\project_mobile\\project_mobile_be\\src\\main\\java\\tdc\\edu\\vn\\project_mobile_be\\services\\impl

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

rabbitmq:
  host: localhost
  port: 5672                     # Changed port for application use
  username: guest
  password: guest
  virtual-host: /
  connection-timeout: 60000

  publisher:
    confirm-type: correlated
    returns: true

  listener:
    simple:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 2
      prefetch: 1
      acknowledge-mode: auto
      concurrency: 1
      max-concurrency: 5

logging:
  level:
    org:
      springframework:
        web:
          socket:
            messaging:
              StompSubProtocolHandler: TRACE
        messaging:
          simp:
            stomp:
              StompDecoder: TRACE

websocket:
  message-size-limit: 2MB
  buffer-size-limit: 2MB
  send-time-limit: 10000
=======
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
    server:
      port: 8080
      file:
        upload-dir: C:\Users\Vinh\Desktop\project_mobile\project_mobile_be\src\main\java\tdc\edu\vn\project_mobile_be\services\impl
        springdoc:
          swagger-ui:
            enabled: true
          api-docs:
            enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: thietasasasa@gmail.com
    password: wcrs zxrv wofz bfje
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt:
  signerKey: "CHpSZnAya03fnmgaxVnU9u4gdxZvnx+UFcrrC5i9+ZwI4+f5CNP0BlQEDCjNeyHh"
  valid-duration: 60
  refreshable-duration: 7


spring.devtools:
  restart:
    enabled: true  # Kích hoạt tự động tải lại
    exclude: static/**,public/** # Loại trừ thư mục static và public
    spring:
      jackson:
        time-zone: Asia/Ho_Chi_Minh
redis:
    host: 192.168.57.128
    port: 6379
    password: ''


google:
  cloud:
    storage:
      bucket-name: mobileproject
    credentials:
      path: src/main/resources/service-account.json
>>>>>>> dev
